[[drone]]
id = 1
pdr = 0.1
connected_node_ids = [5, 6, 100]

[[drone]]
id = 2
pdr = 0.15
connected_node_ids = [5, 6]

[[drone]]
id = 3
pdr = 0.2
connected_node_ids = [7, 8]

[[drone]]
id = 4
pdr = 0.05
connected_node_ids = [7, 8]

[[drone]]
id = 5
pdr = 0.12
connected_node_ids = [1, 2, 9,101]

[[drone]]
id = 6
pdr = 0.08
connected_node_ids = [1, 2, 20]

[[drone]]
id = 7
pdr = 0.1
connected_node_ids = [3, 4, 9]

[[drone]]
id = 8
pdr = 0.07
connected_node_ids = [3, 4, 10,102]

[[drone]]
id = 9
pdr = 0.09
connected_node_ids = [5, 7]

[[drone]]
id = 10
pdr = 0.11
connected_node_ids = [6, 8,102]

[[client]]
id = 100
connected_drone_ids = [1]

[[client]]
id = 101
connected_drone_ids = [5]

[[server]]
id = 102
connected_drone_ids = [8, 10]