[[drone]]
id = 1
pdr = 0.1
connected_node_ids = [100, 2, 6]

[[drone]]
id = 2
pdr = 0.25
connected_node_ids = [101, 1, 3,7]

[[drone]]
id = 3
pdr = 0.14
connected_node_ids = [2,4,8]

[[drone]]
id = 4
pdr = 0.03
connected_node_ids = [3,5,9]

[[drone]]
id = 5
pdr = 0.05
connected_node_ids = [4,10]

[[drone]]
id = 6
pdr = 0.03
connected_node_ids = [1,7]

[[drone]]
id = 7
pdr = 0.05
connected_node_ids = [2,6,8]

[[drone]]
id = 8
pdr = 0.03
connected_node_ids = [3,7,9]

[[drone]]
id = 9
pdr = 0.14
connected_node_ids = [4,8,10,102]

[[drone]]
id = 10
pdr = 0.1
connected_node_ids = [5,9, 102]

[[client]]
id = 100
connected_drone_ids = [1]

[[client]]
id = 101
connected_drone_ids = [2]

[[server]]
id = 102
connected_drone_ids = [9, 10]

