[[drone]]
id = 1
pdr = 0.1
connected_node_ids = [2, 7]

[[drone]]
id = 2
pdr = 0.15
connected_node_ids = [1, 3, 7]

[[drone]]
id = 3
pdr = 0.2
connected_node_ids = [2, 4, 8, 9]

[[drone]]
id = 4
pdr = 0.05
connected_node_ids = [3, 5, 8, 9]

[[drone]]
id = 5
pdr = 0.12
connected_node_ids = [4, 6, 10]

[[drone]]
id = 6
pdr = 0.08
connected_node_ids = [5, 10]

[[drone]]
id = 7
pdr = 0.1
connected_node_ids = [1, 2, 8]

[[drone]]
id = 8
pdr = 0.07
connected_node_ids = [3, 4, 7, 9]

[[drone]]
id = 9
pdr = 0.09
connected_node_ids = [3, 4, 8, 10]

[[drone]]
id = 10
pdr = 0.11
connected_node_ids = [5, 6, 9]

[[client]]
id = 100
connected_drone_ids = [1]

[[client]]
id = 101
connected_drone_ids = [4]

[[server]]
id = 102
connected_drone_ids = [10]